### ISSUE TITLE
Storage directoy on dev vs. exrm prod

### ISSUE THREAD

**Issue by joshuaswilcox** [stavro/arc#91] opened 2016-07-28 12:04 UTC
when running locally `"uploads/bottle_images/images/#{scope.id}"` works fine and uploads to a directory at the root of my project called `./uploads` but when using exrm to release my app in prod mode, the file get uploaded to `./rel/app/uploads/thing_images/images/294/med_xx.jpg` but the url that is generated is for http://mysite.com/uploads/thing_images/images/294/med_xx.jpg and that does not map to the rel folder, but the the `./uploads` folder

**Comment by stavro** [comment] 2016-07-28 12:08
Can you clarify a little more?  I haven't used exrm yet.

What are the full URLS that you would like to see for dev vs. prod?

**Comment by joshuaswilcox** [comment] 2016-07-28 12:12
i guess I would just prefer if in prod all images were at `./uploads...` instead of `./rel/app/uploads`.  Here is my storage dir

```
  def storage_dir(_version, {_file, scope}) do
    "uploads/bottle_images/images/#{scope.id}"
  end
```
so I can see why with exrm would put them in `./rel/app/uploads` because that becomes the relative directory the app is running, but i am unsure why `Scotchy.Image.url(...)` is not creating the correct links to where the app is running

**Comment by joshuaswilcox** [comment] 2016-07-28 12:19
Here is an example of the difference, local uploads vs prod uploads
```
./uploads/bottle_images/images/85/large_Bowmore18-LARGE.jpg
./uploads/bottle_images/images/85/Bowmore18-LARGE.jpg
./uploads/bottle_images/images/85/med_Bowmore18-LARGE.jpg
./rel/scotchy/uploads/bottle_images/images/296/med_mars-awai-tradition-new-bottle-40.jpg
./rel/scotchy/uploads/bottle_images/images/296/original_mars-awai-tradition-new-bottle-40.jpg
```

**Comment by stavro** [comment] 2016-07-28 12:25
In this case, the working directory of the app appears to be `/rel/scotchy`.  So the files are saved in `./uploads` relative to that directory, and the urls are created similarly.

Would the URLs even work if it was generated as 

 `http://mysite.com/rel/scotchy/uploads/bottle_images/images/296/original_mars-awai-tradition-new-bottle-40.jpg`?

**Comment by joshuaswilcox** [comment] 2016-07-28 12:26
No i just tried that that, you can see here http://joshuawilcox.net:4444/rel/scotchy/uploads/bottle_images/images/296/original_mars-awai-tradition-new-bottle-40.jpg i think it might have to do with how the compiling of exrm works, so maybe i can just create a symlink on the server

**Comment by stavro** [comment] 2016-07-28 12:28
Thanks - I'm going to consider this a duplicate of https://github.com/stavro/arc/issues/80 and https://github.com/stavro/arc_ecto/issues/4

**Comment by joshuaswilcox** [comment] 2016-07-28 12:29
Sounds good thanks

**Closed by stavro** 2016-07-28 12:28 UTC

**Comment by Fadhil** [comment] 2016-08-10 11:53
@joshuaswilcox when you make a release with exrm on prod, do you run it with `mix phoenix.server` or with the exrm `/apps/my-app start` ? I do it the 2nd way, and when I specify "uploads" as the directory, the generated URL is correct (it goes to uploads), but the actual directory is in `/apps/my-app/uploads` instead of being in `priv/static/uploads` (as it would be in development. What do?

**Comment by Fadhil** [comment] 2016-08-10 13:55
Ok, so the fix for this is to Plug.Static with a `from:` directive that points to a filesystem dir.
https://hexdocs.pm/plug/Plug.Static.html has some documentation on `from`

Mine eventually looked like this: 

```
 plug Plug.Static,
 at: "/uploads", from: "/apps/flexphoenix/uploads/", gzip: false
```

**Comment by OvermindDL1** [comment] 2016-08-10 15:24
For note, everything is application relative, and files 'should' only be stored inside priv in most cases.  I'd recommend defaulting to storing in "<priv>/uploads" or so or make it a user-configurable location in the config file (or via the system environment).

**Comment by jerodsanto** [comment] 2016-08-10 15:48
The problem with uploading to `priv/static/uploads` is that if/when you run `mix phoenix.digest` it will digest the uploaded files. Also, it seems odd to say that uploaded files are `static`, since by their very nature they are dynamic.

I'm having them put in `priv/uploads`, having Phoenix serve static from there in dev, and then telling Nginx to serve from their in prod. However, when we push a new release it will completely overwrite the `priv` directory during compilation. Is that common? I thought `priv` is supposed to be left alone for this very purpose?
